on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_ibcdatajson:
    name: Validate memo keys schemas
    runs-on: ubuntu-latest
    steps:
      - name: checkout registry
        uses: actions/checkout@v3
          
      - name: Install JSON-Schema-Validator
        run: npm install -g jsonschema

      - name: Validate Memo Keys schemas
        run: |
          for file in $(find . -name '*/_memo_keys/*.json'); do
            if ! jsonschema -i "$file" ./memo_keys.schema.json; then
              exit 1
            fi
          done
